version: "3.8"
services:
  utopia-config-service:
    image: 247293358719.dkr.ecr.us-east-1.amazonaws.com/dev/ss-utopia/config-server:latest
    ports:
      - 8888:8888
    env_file:
      - ./.secret/spring_config_encrypt_key.env
      - ./profile.env
  utopia-auth-service:
    image: 247293358719.dkr.ecr.us-east-1.amazonaws.com/dev/ss-utopia/auth-service:latest
    ports:
      - 8089:8089
    depends_on:
      - utopia-config-service
    env_file:
      - ./profile.env
  utopia-customers-service:
    image: 247293358719.dkr.ecr.us-east-1.amazonaws.com/dev/ss-utopia/customers-service:latest
    ports:
      - 8081:8081
    env_file:
      - ./profile.env
    depends_on:
      - utopia-config-service
      - utopia-auth-service
  utopia-flights-service:
    image: 247293358719.dkr.ecr.us-east-1.amazonaws.com/dev/ss-utopia/flights-service:latest
    ports:
      - 8083:8083
    env_file:
      - ./profile.env
    depends_on:
      - utopia-config-service
  utopia-tickets-service:
    image: 247293358719.dkr.ecr.us-east-1.amazonaws.com/dev/ss-utopia/tickets-service:latest
    ports:
      - 8082:8082
    env_file:
      - ./profile.env
    depends_on:
      - utopia-config-service
  utopia-orchestrator-service:
    image: 247293358719.dkr.ecr.us-east-1.amazonaws.com/dev/ss-utopia/orchestrator-service:latest
    ports:
      - 443:443
    env_file:
      - ./profile.env
    depends_on:
      - utopia-auth-service
      - utopia-customers-service
      - utopia-flights-service
      - utopia-tickets-service
x-aws-cloudformation:
  Resources:
    UtopiaorchestratorserviceTCP443Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:us-east-1:247293358719:certificate/c6d90f51-d983-4f97-b5a6-1916de46f169"
        Protocol: TLS
    Route53RS:
      Type: AWS::Route53::RecordSet
      Properties:
        Name: dev-services.utopia-air.click
        Type: A
        AliasTarget:
          DNSName:
            Fn::GetAtt: LoadBalancer.DNSName
          HostedZoneId:
           Fn::GetAtt: LoadBalancer.CanonicalHostedZoneID
        HostedZoneId: Z07227751H35Z7E3SB7PD
